[project]
name = "feb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "polars>=1.38.1",
    "seaborn>=0.13.2",
    "sympy>=1.14.0",
    "tabulate>=0.9.0",
]
